version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./register:/var/www/html
    depends_on:
      - mailhog
    expose: # Nginxからアクセスするためexpose
       - "9000"
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./register:/var/www/html
    depends_on:
      - app
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

